### ISSUE TITLE
OAuth fatal error when starting up

### ISSUE THREAD

**Issue by jasonszhao** [TheSlideGuy/theslideguy#3]
Below is the message:

```
/Users/Jason/Repositories/TheSlideGuy/node_modules/passport-oauth2/lib/strategy.js:80
  if (!verify) { throw new TypeError('OAuth2Strategy requires a verify callbac
                       ^
TypeError: OAuth2Strategy requires a verify callback
    at new OAuth2Strategy (/Users/Jason/Repositories/TheSlideGuy/node_modules/passport-oauth2/lib/strategy.js:80:24)
    at Object.<anonymous> (/Users/Jason/Repositories/TheSlideGuy/server/server.js:53:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by nerdondon** [comment]
Yea the checked in stuff isn't working. It was just to show work in
progress and a change in direction via integration with planning center

Below is the message:

/Users/Jason/Repositories/TheSlideGuy/node_modules/passport-oauth2/lib/strategyjs:80
  if (!verify) { throw new TypeError('OAuth2Strategy requires a verify callbac
                       ^
TypeError: OAuth2Strategy requires a verify callback
    at new OAuth2Strategy
(/Users/Jason/Repositories/TheSlideGuy/node_modules/passport-oauth2/lib/strategyjs:80:24)
    at Object<anonymous>
(/Users/Jason/Repositories/TheSlideGuy/server/serverjs:53:21)
    at Module_compile (modulejs:460:26)
    at ObjectModule_extensionsjs (modulejs:478:10)
    at Moduleload (modulejs:355:32)
    at FunctionModule_load (modulejs:310:12)
    at FunctionModulerunMain (modulejs:501:10)
    at startup (nodejs:129:16)
    at nodejs:814:3

—
Reply to this email directly or view it on GitHub
<https://github.com/TheSlideGuy/theslideguy/issues/3>.
